In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:

df=pd.read_csv('/content/drive/My Drive/Data Mining in Science/praktikum/3. Klasifikasi/iris_species.csv').dropna()

#Create numeric classes for species (0,1,2) 

df.iloc[df['Name']=='Iris-virginica','species']=0
df.iloc[df['Name']=='Iris-versicolor','species']=1
df.iloc[df['Name']=='Iris-setosa','species'] = 2

      Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        2
1   2            4.9           3.0            1.4           0.2        2
2   3            4.7           3.2            1.3           0.2        2
3   4            4.6           3.1            1.5           0.2        2
4   5            5.0           3.6            1.4           0.2        2

In [0]:
X = df.iloc[:, 1:5].values
y = df.iloc[:, 5].values


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_geography = LabelEncoder()
X[:, 1] = le_geography.fit_transform(X[:, 1])
le_gender = LabelEncoder()
X[:, 2] = le_gender.fit_transform(X[:, 2])
ohe = OneHotEncoder(categorical_features=[1])
X = ohe.fit_transform(X).toarray()
 avoid dummy variable trap
X = X[:, 1:]

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# creating ANN classifier
classifier = Sequential()
# one rule to determine the number of hidden layers
# is to average the number of input and output nodes
classifier.add(Dense(units=6, input_dim=11, kernel_initializer='uniform', activation='relu'))
# Add second hidden layers
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
# output layer
# also replace activation function to sigmoid to have probabilities
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
# compile the classifier
# adam is a type of SGD
# crossentropy is log loss function, for binary classification, use 'binary_crossentropy' 
# for multiclass classification, use 'categorical_crossentropy'
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
classifier.fit(X_train, y_train, epochs=10, batch_size=10)




Epoch 1/10





120/120 [==============================] - 1s 7ms/step - loss: 0.6908 - acc: 0.3083
Epoch 2/10
120/120 [==============================] - 0s 190us/step - loss: 0.6845 - acc: 0.3083
Epoch 3/10
120/120 [==============================] - 0s 170us/step - loss: 0.6772 - acc: 0.3083
Epoch 4/10
120/120 [==============================] - 0s 138us/step - loss: 0.6664 - acc: 0.3083
Epoch 5/10
120/120 [==============================] - 0s 173us/step - loss: 0.6488 - acc: 0.3083
Epoch 6/10
120/120 [==============================] - 0s 172us/step - loss: 0.6252 - acc: 0.3083
Epoch 7/10
120/120 [==============================] - 0s 156us/step - loss: 0.5891 - acc: 0.3083
Epoch 8/10
120/120 [==============================] - 0s 150us/step - loss: 0.5356 - acc: 0.3083
Epoch 9/10
120/120 [==============================] - 0s 149us/step - loss: 0.4687 - acc: 0.3083
Epoch 10/10
120/120 [==============================] - 0s 159us/step - loss: 0.3792 - acc: 0.3083


In [0]:
from sklearn.metrics import confusion_matrix
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(confusion_matrix(y_test, y_pred))

[[ 0  6  0]
 [ 0 13  0]
 [ 0 11  0]]


In [0]:
(1566+111)/(1566.0+29+294+111)

0.8385